name = "LeanFomega"
version = "0.1.0"
defaultTargets = ["leanfomega"]

[[require]]
name = "lean-subst"
scope = "amarmaduke"
git = "https://github.com/amarmaduke/lean-subst"
rev = "705cab3ccd836e96b6051ec4d69f63f25eecac70"

[[lean_lib]]
name = "LeanFomega"

[[lean_exe]]
name = "leanfomega"
root = "Main"
